---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lcg.
--- DateTime: 2020/8/24 9:30 下午
---

---@class BaseClass
BaseClass = class("BaseClass")

function BaseClass:ctor(param)

    self.param = param
    print("BaseClass:ctor Invoked and param = " .. tostring(param))
end

function BaseClass:Call()
    
    print("BaseClass:Call Invoked")
end

return BaseClass