---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lcg.
--- DateTime: 2020/8/24 9:31 下午
---

---@class SubClass
SubClass          = class("SubClass", BaseClass)

SubClass.__create = function()
    
    local _value
    
    function SubClass:ctor()
        
        print("SubClass:ctor Invoked")
        self.super:ctor("ParamFromSubClass")
    end
    
    function SubClass:Call()
        print("SubClass:Call Invoked")
        self.super:Call()
    end
    
    function SubClass:GetValue()
        return _value
    end
    
    function SubClass:SetValue(val)
        _value = val
    end
    
    return {}
end

return SubClass

