---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lcg.
--- DateTime: 2020/8/24 9:31 下午
---

SubClass          = class("SubClass", BaseClass)

SubClass.static =
{
    NAME = "static name"
}

SubClass.__create = function()
    
    ---@class SubClass
    local Instance = {}
    
    local _value
    
    function Instance:ctor()
        
        print("SubClass:ctor Invoked")
        --调用父类构造函数
        self.super:ctor("ParamFromSubClass")
    end
    
    function Instance:Call()
        print("SubClass:Call Invoked")
        --调用父类方法
        self.super:Call()
    end
    
    --获取私有变量
    function Instance:GetValue()
        return _value
    end
    
    function Instance:GetStaticValue()
        --获取类的静态字段
        return self.static.NAME
    end
    
    --设值私有变量
    function Instance:SetValue(val)
        _value = val
    end
    
    return Instance
end

