---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lcg.
--- DateTime: 2020/8/25 5:00 下午
---

require "oop.Class"

require "examples.BaseClass"
require "examples.SubClass"

print("------Test New Lua Base Object------")
print("Test Constructor: ")
local baseInstance = BaseClass.new("ParamFromBaseClass")
print("Test Call Function")
baseInstance:Call()
print("Test Read Public Variable: " .. baseInstance.param)
print("")

print("------Test New Lua Sub Object------")
print("Test Constructor:")
local subInstance = SubClass.new()
print("Test Call Override Function")
subInstance:Call()
print("Test Read Super Public Variable: " .. subInstance.param)
print("")

print("------Test Lua Object UpValue------")
local sub1 = SubClass.new()
local sub2 = SubClass.new()
sub1:SetValue(3)
sub2:SetValue(5)
print("sub1 GetValue = " .. tostring(sub1:GetValue()))
print("sub2 GetValue = " .. tostring(sub2:GetValue()))
print("")
